### ISSUE TITLE
"Select Home Grid for creating global Grid" don't show the real home grid set

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#165]
**Describe the bug**
When you select another grid in "Select Home Grid for creating global Grid" and Reset the "Global Grid" in order to apply the new home board selected, the new board is changed in home button but doesn't change in "Select Home Grid for creating global Grid" menu. 

**Expected behavior**
We expect that "Select Home Grid for creating global Grid" shows the real home grid set in the home button.

**Comment by klues** [comment]
Currently the "home grid" isn't saved anywhere but in the navigation action of the "home" element in the global grid. So it would be theoretically possible to extract it from there, however it's not robust since the global grid could be altered freely and maybe not even have an "home" grid element. So I would have to save the data of which is the home grid somewhere else just for this select box. I think since it says "Select home grid for **creating global Grid**" it's not that much of an issue that it doesn't show the current "home grid".

Therefore I'll close the issue, but feel free to comment again.

**Comment by arasaac-dga** [comment]
Ok, understand. Thanks for the explanation.
