### ISSUE TITLE
Button to download offline /cache all images at once

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#184]
Many people has commented that need to be sure that all the images/symbols are downloaded and cached in the device before switching off the Internet. In many cases they don't want that user has Internet conexion. They are requesting a button (in the top of the grid manage page) or an option in "More" options of the grid manage page to make a process similar to generate thumbnails that download/cached all the images and symbols used in the communicator.

**Comment by klues** [comment]
This is already implemented: Three seconds after importing a new configuration all images that are saved as link are automatically pre-cached in the background. Depending on the device, internet connection and number of elements in the configuration, this needs some time - on my computer about 10 seconds.
Maybe we should just make this process more transparent to the user by showing a popup at the bottom?! I don't know if we then need an extra possibility to trigger it manually, since I think there is no situation where it makes sense: if people are adding images using the integrated online search, all these images are also automatically cached. Manually trigger it would only make sense if someone imports a backup without included image data (also see https://github.com/asterics/AsTeRICS-Grid/issues/186 ) while not being online - I don't know how often this will happen?!

**Comment by arasaac-dga** [comment]
Ok. We also think that when backup files with included images are developed, it would be enough with a pop-up making more transparent the process and advice when it has finished and all the images have been cached. We understand that this process is triggered too when somebody makes a change in an online account and the change is synchronized in the destiny device (in case a new image is added for example). Isn't it?

**Comment by klues** [comment]
I've now added this, which wasn't done before:
* if an image (from an API) is changed/added for an online user, the image is also automatically cached on other devices, when the change of the image is pulled from the database.
* at logging in for the first time to an existing online user, all images are cached after the first complete synchronization.

So I think this should cover all cases to always have all images cached.
However I'm not sure about showing any notifications to users. I think everyone expects that the images are still there while working offline, so it's maybe confusing to get any notification that the caching of images has finished. I think we maybe should keep it in the background.

**Comment by klues** [comment]
please test at https://grid.asterics.eu/latest/

**Comment by arasaac-dga** [comment]
Tested. Works as expetected.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-01-17-14.54%2F%2B0100
