### ISSUE TITLE
Periodically advice about the need of make backups

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#187]
@klues commented to us in some previous emails about this feature and we consider that is very interesting due the need to be sure that people store "offline" the communicator data. A pop-up message must appear periodically remembering to the user the need to make backups. Perhaps it could be an "user" option in configuration in which you can set the interval of time (days) for messages or deactivate in case you don't need them.

**Comment by klues** [comment]
I've implemented it like this:
* everytime a grid is saved, the time of the change is also saved
* in the settings there is a new option to set a notification interval for backups at the bottom of the page at the heading "Notifications" (if set to `0`, no notifications are shown)
* in the background there is a check all x hours and if both of these conditions are met a notification for backup is shown:
   * the time of the last notification to now was longer than the set notification interval in the settings
   * there was no backup made + changes done in the configuration since the last backup and the last backup was done a longer time ago than the set notification interval in the settings
* after importing a backup / default configuration, the state is also set to "backed up" and therefore no notification is shown

This is what the notification looks like:
![grafik](https://user-images.githubusercontent.com/2537025/212133535-9763aa02-da08-4279-bde4-a606ecaf964e.png)

For testing the check for displaying to notification is set to 2 seconds and the set interval from settings is interpreted in seconds instead of days.
Please test at https://grid.asterics.eu/latest/

For the intervals I would propose:
* Interval for background check for deciding if the notification should be shown: 6 hours
* Default setting of interval of showing the notification: 14 days?!

I've just noticed that for an existing user I don't get any notification, that should be changed.

**Comment by arasaac-dga** [comment]
Ok, we have tested and works as expected and you comment. The intervals proposed seem to be suitable.

**Comment by klues** [comment]
OK, what do you think if people should now get notifications by default when installing this update? Some of them probably have the default configuration, where a backup is not needed, some of them have custom configurations, where a backup would make sense. It's not easy to test if users have a default or custom configuration, I would have to compare to all existing default configurations.

As soon as users change something after the update, it will be noticed and the notification will be shown. But before maybe we shouldn't show it in order to not disturb everyone by default?! What do you think?

**Comment by arasaac-dga** [comment]
We think that the reminder must be activated and shown to all the users once you add to the main version in order users know the new feature. Most of the users modify the communicators although take a predefined one initially. So, better to activate by default for all the users.

**Comment by klues** [comment]
I've done:
* changed intervals for checking for main version: check 60 seconds after login, then every 60 minutes. Default interval for reminding: 7 days.
* for existing users a notification is shown, for users without grids no notification is shown
* when changing users, the tooltip is cleared (and a playing webradio is stopped)

please test at https://grid.asterics.eu/latest/

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-01-17-14.54%2F%2B0100
