### ISSUE TITLE
Dual Language setup doesn't allow to specify different speakers to be selected

### ISSUE THREAD

**Issue by TrickyNFTs** [asterics/AsTeRICS-Grid#208]
in the settings you can only specify one speaker for all grids, it would be good to have the setting for each grid, or for each language. E.g. I translate into valenciano but use the katalan speaker. This doesn't work with auto-choosen-language setup in dual language environments. so a mapping of favourite speakers for choosen languages would be nice, that way it would also be possible to map non-existing speakers to languages that more or less fit (like catalan to valencian)

**Comment by TrickyNFTs** [comment]
now you can change the language and the speaker, but the speaker has to be from the same language. for languages without speaker this means no choice but "automatic", missing a clickbox with "show all speakers" to be able to select the most fitting speaker from the same language-family for non supported languages. this would make possible selections like e.g. select language valancian with speaker catalan, to have a fitting speaker. workaround is do the valencian-translation as "catalan", but if you want to enable e.g. valancian AND catalan language setup you would want to do the translation in the correct language, resulting in being unable to select a speaker for catalan.

**Comment by klues** [comment]
OK, thanks for the hint. Another problem is that currently the text that is being spoken is determined by the language of the voice. So if you e.g. have set the content language to English (texts in grids are shown in english) and a Spanish voice, then the spanish translations will be spoken with the spanish voice (if the translation is available), while the texts are shown in english. This is also a use case that is wanted by some users, but I think I should add an option like `link voice language to spoken translation` in order to turn on/off this behaviour. Additionally I can add a checkbox `show all voices` in the change voice action, then your use case to use a Catalan speaker for Valencian translations would also work.

**Comment by klues** [comment]
@arasaac-dga: could you please also test this and give your feedback?

**Comment by arasaac-dga** [comment]
We have tested and works as expected and offer more options to "play" with languages and voices. For example, in Spanish you can change the voices to different dialects without changing the language with different buttons. And help to solve the problem with languages that do not have voices (using the voice of other similar languages).

**Comment by klues** [comment]
Thanks for confirming, released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-01-17-14.54%2F%2B0100
