### ISSUE TITLE
Home Grid must not show when "not reachable grids" are selected in grids filter (in manage grids)

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#226]
"not reachable grids" is an useful filter to facilitate the "cleaning" (delete) of grids that are not in use and not linked. Showing Home Grid is confusing because, being the initial grid is not linked from another grid, but it's used because it is the first one. So, we consider that Home Screen must not be shown when this filter is used.

**Comment by klues** [comment]
I agree, but unfortunately it's not easy, since currently I'm not explicitly saving the home grid. However since it's also related to other issues like https://github.com/asterics/AsTeRICS-Grid/issues/202, I think it would make to explicitly save it somewhere. For the keyboard shortcut `Ctrl + Pos1` for navigating to the home grid, I'm also using an ugly hack to determine which grid is the home grid: https://github.com/asterics/AsTeRICS-Grid/blob/master/src/js/service/keyboardShortcuts.js#L29 - this also could be improved when implementing this.

**Comment by arasaac-dga** [comment]
Ok, We understand. Then link this issue with the others and when this information is stored in some way it will be possible to solve all the issues and features involved.

**Comment by klues** [comment]
Added possibility to select home grid at the bottom of "Manage grids":
![grafik](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/f3f3b1fa-43ba-4639-9966-cbe31dc6d59f)

If defined, the home grid now isn't listed in "not reachable grids" anymore.

Released to grid.asterics.eu/latest/ - please test.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-01-03-12.25%2F%2B0100
