### ISSUE TITLE
Tranlation / Sorting of language names

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#230]
In the dialog "Grids übersetzen" the target language of the right column can be selected.
The choice of languages is obviously sorted based on another language, because German (Aleman) is located after the letter "C".
![grafik](https://user-images.githubusercontent.com/4621810/213433096-3483e190-6451-43d9-a994-483b90af8dc4.png)

## Suggested Solution

Either always use English language names or sort the names after the translation. This is probably also the case for other language selection dialogs.

**Comment by klues** [comment]
Thanks for reporting. I think the problem was that I was translating the language using the content language and not the current application language. I've now changed the texts in the dropdown and the labels "Texte auf <lang>" to be translated using the application language, which in general is more consistent.

Please test at https://grid.asterics.eu/latest/

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-02-10-12.55%2F%2B0100
