### ISSUE TITLE
Home menu vs. Home Grid

### ISSUE THREAD

**Issue by rgabo74** [asterics/AsTeRICS-Grid#238]
It is a bit confusing that the `Home` navigation button in the left side menu does not take me to the `Home Grid` that I define. The Home menu takes me to the last grid I used.

It would probably make sense to rename the `Home` menu to `Grids` or change the business logic to jump to the home grid when `Home` menu is pushed.

**Comment by klues** [comment]
Thanks for the comment, I agree. However currently the home grid isn't explicitly stored somewhere (only within the navigation of the "house" symbol in the global grid) - this should be changed, since it's also causing other issues like https://github.com/asterics/AsTeRICS-Grid/issues/226 and https://github.com/asterics/AsTeRICS-Grid/issues/202. So then it'll be possible to define and change the home grid somewhere in the config. Currently it's only possible to define the home grid, which should be used to generate a new global grid, but as said, afterwards it's only saved within the "home" navigation of the global grid:

![image](https://user-images.githubusercontent.com/2537025/217754009-1a23cf40-5600-4bb1-8dc4-e146d8e7f61e.png)

**Comment by klues** [comment]
Added possibility to select home grid at the bottom of "Manage grids":
![grafik](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/f3f3b1fa-43ba-4639-9966-cbe31dc6d59f)

If defined, the "Home" menu now navigates to the home grid.

Released to [grid.asterics.eu/latest/](https://grid.asterics.eu/latest/) - please test.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-01-03-12.25%2F%2B0100
