### ISSUE TITLE
Introduce sub-pages with built-in navigation for paging

### ISSUE THREAD

**Issue by rgabo74** [asterics/AsTeRICS-Grid#272]
Sometimes the number of tiles of the same type is too many to conveniently fit a single page. It can be difficult for selecting from a grid of 16 or 20 tiles both visually, both because of complexity.

It would be nice to be able to define multi-page grids which are same in dimensions and layout, but they are having left-right navigation buttons where editors and users can page among sub-pages, so tiles can be structured better with smaller number on each sub-page.

This functionality is quite cumbersome to define with the current capabilities of the UI.

**Comment by klues** [comment]
Do you mean something like this: https://github.com/asterics/AsTeRICS-Grid/issues/257 - to be able to make grids which can be scrolled horizontally or vertically?

Otherwise, if you want to navigate using buttons (= grid elements?!), what do you want achieve that is different from just linking multiple grids as "subpages", like this:

![image](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/acc20263-eb35-43d8-8c38-7439f488caea)

Also see this demo configuration: [test_2023-05-15_13-22_asterics-grid-custom-backup.zip](https://github.com/asterics/AsTeRICS-Grid/files/11477197/test_2023-05-15_13-22_asterics-grid-custom-backup.zip)

**Comment by rgabo74** [comment]
We now implemented the navigation through sub-pages as you suggested below. Scrolling would probably also work in our use case, but it would be challenging to make it work with all various input methods. I think we will be all right now with manually built paging. Thanks for the hint.
    On Monday, May 15, 2023 at 01:24:51 PM GMT+2, Benjamin Klaus ***@***.***> wrote:  
 
 


Do you mean something like this: #257 - to be able to make grids which can be scrolled horizontally or vertically?

Otherwise, if you want to navigate using buttons (= grid elements?!), what do you want achieve that is different from just linking multiple grids as "subpages", like this:



Also see this demo configuration: test_2023-05-15_13-22_asterics-grid-custom-backup.zip
