### ISSUE TITLE
Add an option in "Save as PDF" to print or not the global grid in each page

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#277]
The idea is to add an option that allow that the Global Grid is shown (or not) in each page (grid) of the communicator (without the first row of it where is the accumulated phrase or being this another option) in order to have a real print clone of our communicator that allow to work with the user in other contexts that is not possible with the electronic device or need to have a "paper backup".

**Comment by klues** [comment]
probably best to implement after https://github.com/asterics/AsTeRICS-Grid/issues/228

**Comment by arasaac-dga** [comment]
Yes, sure better to develop first this issue that is more important and related to this but it's something that users request frequently as we prefer to add here to not forget it ;-)

**Comment by klues** [comment]
another idea for improvements: do not only support a thumb index with numbers, but also with grid names, like @willwade suggested in https://github.com/asterics/AsTeRICS-Grid/issues/320#issuecomment-1695179089

**Comment by arasaac-dga** [comment]
Yes, it could be a good idea to replace numbers by text in footer index, although our main worry is the text size in case of long names. In cells we would remain as is now with page numbers (to not saturate the cell). On the other hand we are agree with @willwade suggestion about to design some kind of tabs for print versión of the communicator (in this case it wouldn't neccesary interactive pages). It's a suggestion that some users have made and indeed we have some users that have made some manual approximations to this solution (but it's hard to compose it manually). 

![Screenshot_51](https://github.com/asterics/AsTeRICS-Grid/assets/82500056/b75db15f-243b-4f97-bbfc-be7ca106bd03)
![Screenshot_52](https://github.com/asterics/AsTeRICS-Grid/assets/82500056/48d924ac-d554-4b70-9da5-bc44430be9e9)

**Comment by klues** [comment]
OK, I think there are different use cases and different things we're talking about:

1. Thumb indexes with numbers, as implemented now
They make sense in combination with the numbers within the elements - the idea is that the user of the printed version (maybe in this case a professional) sees the element "food" with number `3` in it, looks at the index on the bottom, and is able to quickly jump to page `3` in order to find the food.

2. Thumb indexes with grid names and numbers, as @willwade proposed in his comment. It's the same as (1), but with the advantage that it's easier to find something, if you're directly looking for a specific topic, e.g. "food".

3. Indexes that consist of grid elements with images, like in the pictures from @arasaac-dga. This is probably the best approach for AAC users, because they can quickly find their grids with the help of the symbols. In this case some kind of "main grid" linking to subgrids is replaced by the index.

I assume that (3) would be most beneficial to implement for most users?! But maybe in a way that is a mixture of (1-3) where the index is smaller than in the pictures from @arasaac-dga and it is configurable if they show numbers, pictures and/or grid names.
I don't think it makes sense to implement some automatic way of generating something that looks exactly like the pictures (with elements in the index in the same size as the other elements), because it would need much space on an A4 paper and in result the work of cutting the white space away would be the same as now cutting the "main grid" and glueing it to the sides of the other printed grids.

**Comment by arasaac-dga** [comment]
Yes, option 3 is most useful because most of the professionals and families want to print the communicator. For this case the interactive index (option 1) it's not useful and yes the tab solution (with the options you comment on select only text, text and pictograms or only pictograms in the tab). So, we consider that it would be neccesary to create a new option to create the "print tabs" that allow in some cases that someone make a print and an interactive pdf. About the design of the tabs we agree with you that it must be smaller and optimize the space. Take in mind that the example that we have shown is composed manually using the board's cells. But we agree that it's necessary to optimize the space and the design.

**Comment by klues** [comment]
I've implemented initial request of this issue, there is now an option `Include global grid` at exporting to pdf. Please test at "latest".

For the index thing, I think we should maybe add a new issue then.

**Comment by arasaac-dga** [comment]
Great!!! Works as expected "Include Global Grid". Thanks For index as you consider. Open it as new issue if you consider better.

**Comment by klues** [comment]
I've created a follow-up issue: https://github.com/asterics/AsTeRICS-Grid/issues/434

The "include global grid" was released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-10-10-09.52%2F%2B0200
