### ISSUE TITLE
Voice setting must not be synchronized in online accounts due the use in different devices with different voices

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#307]
We think that voice selection in setting page must not be synchronized in online accounts because generates problems due that the user does not realise that voice has been misconfigured on the device (when they use the same online account in two different operative systems Windows-Android for example).

**Comment by klues** [comment]
Released to "latest", please test. Voice settings are now not synced anymore, so it's possible to configure them for every device.

Note for testting: I've changed the way of internally saving local configuration settings, so I'm automatically doing some transformation in the background at first time. So please test if voice settings are the same, after initially opening "latest" now. So maybe open "latest" without internet connection once, note the voice settings of the users, update and test if the voice settings are the same afterwards.

**Comment by arasaac-dga** [comment]
We have tested with two users and when we have updated the version in both devices the voice selection was empty (with any selection of voice or automatic). So, we have had to set it up again on both devices. Once made, changes are not sync. We have found a problem with multilingual communicators like yours because the content language still syncs. That generates two problems. First, in user view the communicator doesn't change/refresh the language (you see the old selected language) and you have to refresh the page to see the language updated and second in voice selection inside configuration don't change the voice to other possible voices in the new selected language or Automatic.  So, it generates another collateral problem. Usually if you use a multilingual communicator you set the voice in Automatic but if you have selected a specific language the voice doesn't change. Perhaps content language must not be synced like voice between devices. 

Now we are on holidays until April 8th. So we will not be able to test it until then.

**Comment by klues** [comment]
I've now also moved the content language to the local settings, so it's not synced anymore. I couldn't think of a use case where it should be synced, so I think it's better.

I've also done some tests regarding transforming the data model like this:
1. go to https://grid.asterics.eu/latest/ in order to ensure you have the new "latest" version installed (`release-beta-2024-04-08-15.17/+0200`)
2. go to https://grid.asterics.eu/ and create a new offline user, set some voice settings
3. go to developer tools `Ctrl + Shift + I` and delete the key `AG_USER_SETTINGS` from local storage: https://i.imgur.com/wc4XPTq.png (needed because the transformation is only done once)
4. go to https://grid.asterics.eu/latest/ and check if the voice settings of the new user are still the same and working

For me it worked, I don't know why the transformation didn't work for you at your first test. However I think it's also not  a very big issue, if it's not working automatically, then users have to re-configure their voice settings.

Please test again the change regarding the content language settings, which now isn't synced anymore.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-04-12-11.15%2F%2B0200
