### ISSUE TITLE
Asterics grid - Brazil - best user experience

### ISSUE THREAD

**Issue by LucianaRezende** [asterics/AsTeRICS-Grid#319]
Hello, my name is Luciana Rezende, I am a speech therapist in Brazil. I use Asterics grid and always recommend it to my patients, however I notice some flaws that I think are worth solving for the best user experience. Example:
 1. Sometimes the audio doesn't work, we click on the picture, however it doesn't vocalize, this is unsystematic, it varies from image, and it happens even when we refresh the page, it ends up stressing users.
2. It could have the option of fixing the screen of the AAC board, so that the user does not click on other icons on the tablet, as some still seek to use it for recreation.

Thank you for your attention,
Luciana Rezende

**Comment by ChrisVeigl** [comment]
hi,

regarding 1: 
* which TTS voice do you use (see Settings->Voice) ? It is recommended to use one of the voices which are installed locally on the device (not depending on th einternet connection)
* please make sure to have a stable internet connection at least once when accessing all grid elements, so that the data can be stored locally on your device (after this, the grids should work also without internet connection)

regarding 2:
* did you try the buttons "Fullscreen" and "Lock" on the top right? This should prevent unintended actions / clicks or closing of the application

**Comment by klues** [comment]
Regarding the problems with the voice, please read [this info about voice issues](https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/10_faq.md#issues-with-online-text-to-speech-voices-lags-not-working).

For locking the application please read [this tutorial about locking AsTeRICS Grid](https://aulaabierta.arasaac.org/en/asterics-grid-locking-application-on-android-ios). In addition to locking the menu within AsTeRICS Grid it's also recommended to use the Android or iOS specific features in order to prevent users from leaving the app.

I'm closing this issue, but feel free to still comment or reopen it, if you have further questions.
