### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by tryel** [asterics/AsTeRICS-Grid#32]
During _npm install_ I get this Error:

```
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting _file-saver@1.3.8:_ 
npm ERR! sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI= integrity checksum failed when using sha1: wanted sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI= but got sha512-spKHSBQIxxS81N/O21WmuXA2F6wppUCsutpzenOeZzOCCJ5gEfcbqJP983IrpLXzYmXnMUa6J03SubcNPdKrlg== sha1-5oowx8sETi+zYrQoRp/rKRwuCdg=. (10700 bytes)  
```

**Comment by benjaminaigner** [comment]
Dear @tryel ,

thanks for your interest in AsTeRICS Grid.
Your issue is related to the installation of npm dependencies.

In your case, it fails while installing file-saver dependency.

Please try fixing the installation with these suggestions:
https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0

**Comment by klues** [comment]
thanks @benjaminaigner for the answer. I hope and assume that this fixed the problem, so I'll close this issue. @tryel if you still have issues, just open a new issue.
