### ISSUE TITLE
Export a whole backup for a printable book 

### ISSUE THREAD

**Issue by willwade** [asterics/AsTeRICS-Grid#320]
Right now you can export to PDF for one page - but I'd like to 

- Have a way of Printing a PDF book of a gridset. A whole backup. 
- It should have an option to ignore a row. E.g. the message bar line. I realise people can create these buttons however so just having a way of ignoring that line might make sense
- Add an option to "Print page name" or something - in a cell (look at https://app.globalsymbols.com/en/boardsets/34 for an example in the header). 
- An option to print only pages that connect to other pages. 

And super nice
- Create a way of adding "tabs" to pages. E.g. (hard to see a finished copy - but the templates are https://arasaac.org/materials/en/2952) . I.e at the bottom 2 cm there is a blank space - and a tab that the person cuts out. Its got the page name on it

**Comment by willwade** [comment]
NB maybe similar to #277

**Comment by klues** [comment]
It's already possible to export a whole gridset to PDF:

![image](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/f353bc38-127f-476e-b3a5-7f0808aed5c6)

and then:

![image](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/897fbcfc-a9ef-4d56-8865-b623ed62b753)

You can also print an index at the side of the pages for quickly finding pages after you've put everything into a folder.
For the index you would have to cut away the empty fields marked red:

![image](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/f4ec951b-4fb3-4a41-85e1-92784f55dd7a)

I think maybe it would be better if the numbers in the index would start from the right side, so that in the folder they will start from the top and not from the bottom?!
The other numbers also marked in the screenshot are the pages that are linking/referring to the current page.

> It should have an option to ignore a row.

Yes, this would be good, it's more or less the same as #277.

> Add an option to "Print page name" or something - in a cell (look at https://app.globalsymbols.com/en/boardsets/34 for an example in the header).

I only see the main page of https://app.globalsymbols.com here, please provide a screenshot. As you see in my third screenshot, I already print the name of the grid on the page (next to the numbers)

> An option to print only pages that connect to other pages.

If you select a single grid for export, you already have this option:

![image](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/1573ff36-3382-49a9-9d6b-a09c92ed165c)

It's similar, it exports all grids that are somehow reachable from the current grid.

> Create a way of adding "tabs" to pages.

I think you mean something like the index, I've already explained above?!

**Comment by willwade** [comment]
Wow. That rocks. So yes. Pretty much all there.  I’m away from my computer for a week. Let me look again when I get back next week and show some screenshots.

**Comment by klues** [comment]
I've added the idea with the thumb index to #277, I think all other things are already covered, aren't they?! So I'll close the issue - feel free to reopen or add a new one.
