### ISSUE TITLE
Czech missing in languages list in settings

### ISSUE THREAD

**Issue by mtrakal** [asterics/AsTeRICS-Grid#338]
<img width="1054" alt="image" src="https://github.com/asterics/AsTeRICS-Grid/assets/1458891/b3cd9137-620d-45bb-b539-2376ba97799f">
Czech language is missing in list. 

In case, when I have Chrome set to English as primary language and Czech as other I'm not able to switch app to Czech.

<img width="1227" alt="image" src="https://github.com/asterics/AsTeRICS-Grid/assets/1458891/611553f1-40ab-4be1-af48-24d0becd8f4b">

**Comment by klues** [comment]
The Czech Application language currently isn't released to the main version, it's only available at https://grid.asterics.eu/latest/. But if you are satisfied with all the translations, I can release it to the main version.

**Comment by mtrakal** [comment]
That's weird, because when I open the main version (without /latest/ in url), and have set Czech in browser as primary language it show app in czech. That's the reason why I reported it as a bug :). I'll improve translation while using it but not in a few days. Current translation is quite usable for using app iz Czech :)

**Comment by klues** [comment]
The reason is that the main version and "latest" version aren't completely separated. Only the code is different, not the saved data. The set language is saved in LocalStorage and this is used by both versions, since they are on the same domain. The same for IndexedDB where grid configurations are saved. So if you're selecting Czech in latest version, it's also set in main version. And it seems like the translation file was already there at the moment of the last main release, so it's loaded. The only difference in the "latest" release is, that Czech is shown in the language selection dropdown.
