### ISSUE TITLE
Improve the "Navigate to home grid after selecting an element" option

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#352]
The new feature "Navigate to home grid after selecting an element" added in configuration is a great addition but we think that is neccesary improve them because now is a very global action and sometimes you don't want that this feature is applied. For example in case of use keyboards or Youtube, Radio, Web links actions. So we think is neccesary to add some conditions to disable this feature for specific kind of cells. A possibility could be to add in configuration, next to this option an option to activate/deactivate this option for some kind of listed cells (as commented). So you can deactivate this option for keyboard cells and activate for radio cells, for example.

**Comment by msantos-87** [comment]
I can't think of a case where 'navigating to home grid after selecting an argument' would be useful in the keyboard/radio/podcast sites etc. Maybe a general deactivation for these kind of sites, would be faster/quicker to implement for the moment? Otherwise yes, the option to deactivate 'navigating to home' for specific grids or cells.

**Comment by arasaac-dga** [comment]
Yes general deactivation for this kind of cells with specific actions could be the quickest solution to begin. Perhaps after use some case appear commented by users.

**Comment by klues** [comment]
I would propose to disable "navigate to home after selecting element" for all elements which contain one of these actions:
* `Navigate to other grid` -> this is already the case
* `AsTeRICS action` (activates something in the background via the [AsTeRICS Framework](https://www.asterics.eu/get-started/Overview.html#are) - e.g. sending some infrared command to control a TV)
* `OpenHAB action` - some smart home action using [openHAB](https://www.openhab.org/), e.g. controlling lights or shutters
* `Web radio action`
* `YouTube action`
* `Open website in new tab`

Additionally I would disable "navigate to home after selecting element" for grids which appear to be a keyboard (I'm already using some kind of heuristics to determine if a page is a keyboard in order to decide if elements are added with a separate space or not to the collection bar - I'll reuse this).

I think this should fine, probably nobody needs to manually define for which buttons "navigate to home after selecting element" should not happen.

**Comment by msantos-87** [comment]
Sounds good!

**Comment by arasaac-dga** [comment]
> I would propose to disable "navigate to home after selecting element" for all elements which contain one of these actions:
> 
> * `Navigate to other grid` -> this is already the case
> * `AsTeRICS action` (activates something in the background via the [AsTeRICS Framework](https://www.asterics.eu/get-started/Overview.html#are) - e.g. sending some infrared command to control a TV)
> * `OpenHAB action` - some smart home action using [openHAB](https://www.openhab.org/), e.g. controlling lights or shutters
> * `Web radio action`
> * `YouTube action`
> * `Open website in new tab`
> 
> Additionally I would disable "navigate to home after selecting element" for grids which appear to be a keyboard (I'm already using some kind of heuristics to determine if a page is a keyboard in order to decide if elements are added with a separate space or not to the collection bar - I'll reuse this).
> 
> I think this should fine, probably nobody needs to manually define for which buttons "navigate to home after selecting element" should not happen.

We agree with those actions and kind of grids you propose although we add "accumulated phrase" action too, because if you are composing a phrase in a subgrid and want, for example to delete a word, the system comes back to the home grid when you press in delete or in play or..... Another thing that "worries us" is the elements that are on Global Grid. We are not sure that you always want elements on Global Grid to come back to the home grid but we are going to think about it. We have not a clear opinion about that at the moment.

**Comment by arasaac-dga** [comment]
After discuss more carefully we though that all the cells in Global Grid must be excluded of "Navigate to home grid after selecting an element" option (part from the actions commented prevously).

**Comment by klues** [comment]
I've implemented it, please test at "latest":
* instead of defining for which actions auto navigation to home should be prevented, I've now defined for which actions it should be allowed, which are: `Change language`, `Speak label`, `Speak custom text`, `Play recorded audio`. For all other actions the auto navigation is prevented. I think this makes more sense, because e.g. for the new word form actions it also will automatically prevented, when released.
* auto-navigation is now prevented for keyboards
* auto-navigation is prevented for elements within the global grid. However note that this now only works in the "latest" version and won't immediately work in "main" version, since it uses code that was introduced for the word forms feature. So it will come to "main" when releasing this feature.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-01-19-09.25%2F%2B0100
