### ISSUE TITLE
El sonido no va bien

### ISSUE THREAD

**Issue by paulalogoanaina** [asterics/AsTeRICS-Grid#362]
Desde la última actualización, al pulsar en las celdas no suena ninguna voz durante varios intentos, o a veces suena con lag.
Esto solo lo he notado desde la última actualización

**Comment by klues** [comment]
Hello,
I assume you're using an online voice, which unfortunately often isn't very reliable.
Please read this https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/10_faq.md#issues-with-online-text-to-speech-voices-lags-not-working and try to install / use an offline voice, read this https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/10_faq.md#installing-additional-voices
I'm closing the issue, since I'm quite sure that this is the problem. But feel free to still comment or re-open it.
