### ISSUE TITLE
Issue with 'speak custom text'

### ISSUE THREAD

**Issue by msantos-87** [asterics/AsTeRICS-Grid#365]
I don't know what others might use the 'speak custom text' option for. For me it makes sense to use that option when the pronunciation is wrong. However, the written word that is then added the collection bar shows the edited pronunciation instead of the "correctly written" word from the element, which looks weird. It makes sense in this case to see the "correctly written" word from the element in the collection bar.

**Comment by msantos-87** [comment]
I just randomly noticed while testing for #254 that any word forms don't work when the action 'speak custom text' is added. That makes sense given that that action is applied to the button overall but of course cancels the usefulness of 'speak custom text' for boards that use word forms. I wonder if there's any way around this.

**Comment by klues** [comment]
There are two ways the "speak custom text" feature is used:
* to fix pronunciation - like you've proposed
* to hide a longer phrase / sentence behind a short label, e.g. "I want some water" behind an element labeled "water"

For the first it's not desired to show the alternative text in the bar, for the second it is (at least I'm assuming it, @arasaac-dga what do you think?). Also see prior issues regarding this topic: https://github.com/asterics/AsTeRICS-Grid/issues/172 https://github.com/asterics/AsTeRICS-Grid/issues/182

> I just randomly noticed while testing for https://github.com/asterics/AsTeRICS-Grid/issues/254 that any word forms don't work when the action 'speak custom text' is added. That makes sense given that that action is applied to the button overall but of course cancels the usefulness of 'speak custom text' for boards that use word forms.

Yeah, that's a good question what should be prioritized, if a mixture of custom text / word forms / grammar correction via ARASAAC API is used. I assume the following:
1. word forms override "speak custom text", so if any word forms are defined, "speak custom text" is ignored
2. word forms and ARASAAC grammar API can be used at the same time, so any sentence created with word forms, is still sent to ARASAAC API (if activated) and the corrected form is used afterwards. @arasaac-dga what do you think?

For fixing pronunciation within word forms, we could add a separate optional field "pronunciation" for each word form, which also can be imported and exported. Then there also wouldn't be any problem with showing wrong words within the bar, since it's clear to show the actual word form, not the pronunciation.

**Comment by msantos-87** [comment]
> For fixing pronunciation within word forms, we could add a separate optional field "pronunciation" for each word form, which also can be imported and exported. Then there also wouldn't be any problem with showing wrong words within the bar, since it's clear to show the actual word form, not the pronunciation.

That would be great!

**Comment by arasaac-dga** [comment]
We agree with Benjamin in both things. 

1) "speak custom text" is a neccesary option to "hide a longer phrase / sentence behind a short label". It's a very neccesary option to users with low language level that begin with AAC implementation. So, please don't modify this option in any case. 

2) "word forms and ARASAAC grammar API can be used at the same time" YES. That's the advantage of our API. The correction is made over the final phrase (be or not correct). So, do not interfere over word form feature in any case.

**Comment by klues** [comment]
Since there is now a separate option to define a pronunciation for word forms, I think this should be used and it doesn't interfere with the existing option "speak custom text".
So now if defined both still "speak custom text" (or "play audio") wins against word forms, however they shouldn't be used both at the same time, since it makes no sense. See my comment here:
https://github.com/asterics/AsTeRICS-Grid/issues/254#issuecomment-1931675212

So I'll close this issue.
