### ISSUE TITLE
last word of a phrase not saved to the dictionary 

### ISSUE THREAD

**Issue by cbernscherer** [asterics/AsTeRICS-Grid#370]
Hi, 

when entering a phrase into the Grid keyboard, the last word will not be stored in the dictionary - see the attached video. 

Best, 
Christian 

https://github.com/asterics/AsTeRICS-Grid/assets/4591723/ca70b6b6-d664-4368-a67e-9e735c1a89fe

**Comment by klues** [comment]
Hi and thanks for your comment!
I don't know exactly how I've implemented it, but I know that I've intentionally prevented adding a word to the dictionary directly in order to prevent adding typos to the dictionary.
E.g. if someone writes "I am Benjamim" I want to prevent that this is directly added to the dictionary, so I'm only adding it after the next word is written (where I assume that the previous word is already reviewed and corrected.

But I'm open to changes. So maybe making this behaviour configurable or changing it the default?!

**Comment by klues** [comment]
I'm closing this issue, since I think @cbernscherer at some time told me via mail that it makes sense the way I've implemented it. However, feel free to reopen.
