### ISSUE TITLE
Issue with predicted words in multilingual keyboard

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#389]
We have created a multilingüal keyboard (4 buttons to change language) that has added 4 dictionaries and we found an issue with word prediction. The problem is that the predictions cells show words in any of the 4 languages, not only in the language that is set in this momment as you expected. So, the keyboard doesn't accomplish with its objetive of communicate and write in one language. 

On the other hand we have found another issue perhaps related with the issue commented. When you press in some predicted word cell, you listen sometimes the word that is going to appear after the one you are seeing in this momment although the word that is added to the accumulated phrase is the one you see in the predction cell. If the predicted word doesn't change there is no problem but if it's going to change is confuse for user due that listen a different word that press.

**Comment by klues** [comment]
> We have created a multilingüal keyboard (4 buttons to change language) that has added 4 dictionaries and we found an issue with word prediction. The problem is that the predictions cells show words in any of the 4 languages,

I've added an option to use the dictionary of the current content language. See the options of action "Fill prediction elements" at the collect element of the global grid:
![image](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/f2e3e569-dea2-47cc-9d22-64193d829f27)

I've also set it as default for the default global grid, so you can just reset the global grid to default in "Manage grids".
You also have to delete and re-import existing dictionaries, since old ones don't have the information about the language saved.

I've also fixed a bug, where predictions of subsequent words were not shown. So now it's again possible to write things like "My name is Benjamin", delete it and afterwards write "My" where "name" is suggested as next word.

Please test at "latest".

> On the other hand we have found another issue perhaps related with the issue commented. When you press in some predicted word cell, you listen sometimes ...

Sorry, but I didn't understand that. Please try to explain again.

**Comment by arasaac-dga** [comment]
We have tried and work fine following the steps you mention. So this part solved. 

About the other problem see this video. As you can see the system "say" the next predicted word (that replace the actual one in one cell), no the one is showed in this momment when you press the actual predicted word. It happens in all the languages (we have tried on Spanish and English).

https://github.com/asterics/AsTeRICS-Grid/assets/82500056/9d34213f-f873-4200-b644-1903db7520c4

**Comment by klues** [comment]
Thanks for explaining, please test the fix at latest.

**Comment by arasaac-dga** [comment]
Yes. Now works as expected. Thanks
