### ISSUE TITLE
Cordova build 

### ISSUE THREAD

**Issue by willwade** [asterics/AsTeRICS-Grid#40]
Any plans to wrap this into cordova to make a Windows/Mac/iOS app? 

That would totally help adoption :)

**Comment by klues** [comment]
Not yet.
But AsTeRICS Grid is developed as an [Progressive Web App (PWA)](https://de.wikipedia.org/wiki/Progressive_Web_App), at least we try to do so. So it's already possible to use it app-like by following these steps (Chrome-like browser on Android, but should work similar also on iOS):
1. open https://grid.asterics.eu/ in the browser
2. go to menu -> "add to start screen"
3. place the icon anywhere on your start screen
4. opening it from there should now look and feel more like an real app, it shouldn't be seen that the app is running in a browser anymore (e.g. no address bar)

**Comment by klues** [comment]
Would there be any advantages of the Cordova build over the Progressive Web App approach I've explained? If no, I'll close this issue.

**Comment by willwade** [comment]
Hmm. Great question. The main thing is common use and installation. Right now I guess people are more used to "installing an app" than saving a bookmark (crazy times!). Put another way - is there any downsides to a PWA?

**Comment by klues** [comment]
Downsides to a PWA are that they cannot access hardware that easily or even not at all. You're always limited to the APIs of the browser, so e.g. camera access possibly would work, but access to the phone's accelerometer would'nt be possible.
I don't know Cordova, but I can imagine that it makes more direct hardware access possible.

Since AsTeRICS Grid (currently) doesn't really need hardware access, I don't see real downsides for a PWA for it. Yeah, maybe installation, but currently I think AsTeRICS Grid isn't used by any random person who is just inststalling an app from the appstore, but only by persons who we know and where we've showed them how to use it.

**Comment by willwade** [comment]
> Since AsTeRICS Grid (currently) doesn't really need hardware access, I don't see real downsides for a PWA for it. Yeah, maybe installation, but currently I think AsTeRICS Grid isn't used by any random person who is just inststalling an app from the appstore,

Yeah - that's fair enough. There isn't much to gain by wrapping this in an app wrapper then - to be honest - moving to an electron app would be really really easy (hint: [electron-builder](https://github.com/electron-userland/electron-builder) - and see our quick demo of this by looking at this commit https://github.com/dasher-project/redash/commit/cba739e68fc184bd16152eda20a452dec14a1bbb). However - in our code - electron isn't great at giving you access to system-specific stuff. So in [pasco](https://github.com/acecentre/pasco/) - we use cordova because we can get access to things like system audio (we split a cue voice and public voice to different audio outputs) - and access system TTS and audio recording features. But sure - I can only see a benefit right now of an installation process but that's not crucial. 

Feel free to close. Good discussion though! :)

**Comment by klues** [comment]
yeah, thanks for your input!
Maybe we'll consider to do Cordova builds in the future, if we also add features that require more system-level-access, but for now I'll close the issue.
