### ISSUE TITLE
Bug in 'translate grid'

### ISSUE THREAD

**Issue by ms-mialingvo** [asterics/AsTeRICS-Grid#431]
When copying the words in 'translate grid', it duplicates each word. This has worked previously without problems. On Safari, Mac.

**Comment by klues** [comment]
I've used the opportunity to improve the "translate grid" dialog in general. There was a bug I've known for a long time - deleting the labels in both languages caused the row to disappear. Additionally I've added some headings and little symbols in order to make it clearer what is being translated, so it looks like this:

<img src="https://github.com/user-attachments/assets/980113ec-6c8b-423d-8374-afadf2cd9fe2" width="400">

There are also (new) special modes for copying and pasting the translations (buttons copy/paste column):
* `normal left click`: all rows are copied / pasted
* `Ctrl + click` on copy: only rows where **the other language** is empty, are copied, so clicking on "Ctrl + Copy column" for "English" in the screenshot, only copies `fruit`, because the German translation is empty.
* `Ctrl + click` on paste: pastes only to empty rows, so e.g. inserting the translated `Obst` for `fruit` in the example
* `Ctrl + Shift + click` on copy/paste: copies and pastes the values including a generated key indicating the position and symbol of the element. This can be used if one wants to transfer translations between two not exactly equal configurations (e.g. some elements added)

Please test if everything works as expected (at least normal copying and `Ctrl + click`).
@arasaac-dga please also test.

**Comment by klues** [comment]
Thanks for testing, I've found a small bug, when copying and pasting with `Ctrl`, it should only copy/paste if there is a translation within the source language. If both are empty, they shouldn't be used for copying/pasting. I've already fixed this.

> The only thing it's that there is no help or text detailing this possibility of using Ctrl+Copy and people, sure, don't know it.

Yes, there are some parts of the app, which don't have a documentation, it's very difficult to keep everything up-to-date. Maybe we'll also do a video about it at some time.

**Comment by ms-mialingvo** [comment]
> Ok, I've tested on macOS 15, Sequoia, Safari 18 via browerstack.com and I coudn't reproduce it. Which versions of macOS and Safari are you using?

I'm using 17.5. However I struggle to properly reproduce it myself, maybe it was something temporary or maybe there was an issue with my file. I know that it happened on different days but at the moment and even before your first answer it's been working fine.

Thanks for the other improvements! :)

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-11-06-11.43%2F%2B0100
