### ISSUE TITLE
hidden labels /manual label size adjustment

### ISSUE THREAD

**Issue by issatt** [asterics/AsTeRICS-Grid#5]
provide the option to add hidden labels and to readjust label size manually

**Comment by klues** [comment]
Hi, very sorry - didn't notice your issue before, I didn't set this (my own) repository to "watch", what a shame.

what do you mean by "hidden labels"? It's already possible to just create elements without labels and then add a "speak custom text" action in order to still speak a text, see https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/05_actions.md#edit-actions-modal

**Comment by klues** [comment]
Closing this because of no response.
Feel free to reopen.
