### ISSUE TITLE
Importing a .grd file which already exists in browser db not working

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#6]
If you import a grid, e.g. Gerald.grd this works fine for the first time:

![Selection_086](https://user-images.githubusercontent.com/4621810/57526558-f86b1280-732d-11e9-8b79-02e28eb6461e.png)

If you change the grid now, like this
![Selection_087](https://user-images.githubusercontent.com/4621810/57526581-10db2d00-732e-11e9-9bf3-4a00f688a3d9.png)

and then want to reimport the original .grd file, you get an error message:
![Selection_088](https://user-images.githubusercontent.com/4621810/57526622-27818400-732e-11e9-9703-a3885da4581c.png)

and the grid is not imported.

This also happens if you don't change anything in the db.

## Expected behaviour
The import should always override what it is currently in the db.

## Workaround
Rename .grd file to something else and import it with the new name.

**Comment by klues** [comment]
Thanks for filing the issue.

The workaround you described is not valid since the error message is about a duplicate database ID, not a duplicate name of a grid.

Currently the only workaround is to delete the conflicting grid before importing. If you are importing a .grd file containing multiple grids, it's maybe the best to simply delete all existing grids before importing (assuming that the grids to import represent a valid, complete set of grids and the old ones are not needed anymore). The currently fastest way to do this is: delete the first grid, confirm the promt with `Enter` and continue pressing `Enter` -> this will delete all grids subsequently since the `Delete` Button will stay focussed and will be triggered again by each hit on `Enter`.

**Comment by klues** [comment]
Worked on this issue today.

To my mind there are two use-cases:

1. A user wants to import all grids from a .grd file, in addition to existing grids
2. A user wants to import a .grd file as a backup - replacing all existing grids

Therefore I've now changed the available options like this:
![Screenshot_1](https://user-images.githubusercontent.com/2537025/61806093-64dab580-ae37-11e9-9b1a-b23db5033820.jpg)

where "import grid(s)" imports the grids in addition to the existing grids and "import backup" deletes all existing grids and then imports the grids from the file.

I removed the options for backing up the whole database to a file since: 

1. most people would be confused what the difference between exporting all grids to file and backing up the whole database is.
2. since the database is now encrypted, a backup of the encrypted database does not make so much sense anymore -> if the user forgets the password, a backup of the encrypted database will be useless.

Tomorrow I'll do some more tests and then release the new version including these changes.

**Comment by klues** [comment]
the fix is now released, please test to confirm.

**Comment by deinhofer** [comment]
hmm, I am not sure if the options make sense.

Why not providing two menu entries:
1. Export grids to file
2. Import grids from file

When exporting, the user is asked to select the grids to export (default all)
When importing the user is asked to select the grids to import (default all) and if they should be added or replace the current grids.

**Comment by klues** [comment]
I'm not sure if the user will benefit from the additional choice which grids to export/import. What would be use-cases where a user wants to import/export just a subset of grids? Maybe for us as developers it's handy some time but for the majority of users (assuming that hopefully this at some day won't be developers ;)) I think the most used features will be:
1. Export all grids to file
2. Import backup from file

for just creating a backup of everything and restoring it. With the current solutions this is possible with 2 clicks, in your suggested solution it would at least need 4 clicks and the user would have to make much more decisions.

I'll close this issue for now, if the discussion continues we should open a new issue for it, since this is just the bug issue which should be resolved now.

**Comment by deinhofer** [comment]
Just tested it. The problem is solved :-)

But I still don't get the meaning of the menu entries:
![image](https://user-images.githubusercontent.com/4621810/77528609-8be9fb00-6e8e-11ea-888d-737ff2e4ee9a.png)

What's the difference between ```Import grids from file``` and ```import backup from file```. That's a bit confusing as both require .grd file which can be one grid or more grids.
It's not clear how to create a backup as there is no ```Create backup``` menu entry. 

It think the wording is confusing, why not change to:
* Export grids
* Import grids
* Delete all grids

**Comment by klues** [comment]
The current release now has changed `Export all grids` to `Export backup` since now metadata (e.g. input method configuration) and dictionaries are also saved within a backup.
Therefore I think `Import backup` now also makes more sense.

In general the difference between `import grids` and `import backup` is that `import backup` deletes everything before importing. I like this functionality since it takes less actions than `delete all grids` and afterwards `import grids`.
Maybe it would be clearer to name it `Reset and import backup`?

**Comment by deinhofer** [comment]
So it would be 

* Export backup
* Import backup
* Import grids

afterwards?

I think ```Reset and import backup``` would also be confusing as resetting means to reset to the default grids and not to delete all grids.

So all forms of export (single grid and backup) will also save the metadata from now on?
Maybe use

* Export backup
* Import backup
* Clear and import backup

**Comment by klues** [comment]
No, only `Export backup` saves dictionaries and metadata, exporting a single grid does not.

In your three suggestions an option for importing something that isn't a backup is missing (single grid or grids from open board format). [Open board format](https://www.openboardformat.org/examples) integration makes things even more complicated.

What about:
* **Export backup**: saves all grids, metadata and dictionaries to file
* **Import grid(s) from file**: imports grids from any supported file (`.grd` backup or single grid, `.obf`, `.obz`). only imports grids, not metadata or dictionaries. Existing grids are not deleted.
* **Clear and import from file**: deletes all grids, imports grids from any file (`.grd` backup or single grid, `.obf`, `.obz`), also imports (and overwrites) metadata and dictionaries if available (which is only the case for `.grd` backup files).

This would be the same as currently implemented in `/latest` , just the last point has to be renamed. I like it because it's not too much options and still everything needed is possible and to my mind it's also quite clear what each option does.
When also implementing export to open board format, I possibly would add an extra option `Export all grids to open board format` or similar.
What do you think?

**Comment by deinhofer** [comment]
I think what's still confusing is that in some case there is metadata and in some case not. Nevertheless the file extension is the same.
What about inventing a second file extension for backups? ```.grb```

Then you could do this:
* Export backup: saves all including metadata
* Restore backup: Restoring a backup makes it very clear that existing grids are replaced.
* Import grids: Those can be single grids in .grd and .obf, .obz...

The ```export grid```  you already have in the grid list. So this would be consistent I think.

**Comment by klues** [comment]
I actually one day already had the `.grb` and `.grd` extension :D
But then I removed it because I thougth that both are just files with one or more grids and the distinction doesn't make sense. But yeah, maybe now it makes more sense again.

What I'm missing in your suggestions: a possibility to delete all grids and import an `.obz` file. This is definitely a use case that will be needed sometimes.

I don't see any cases where my latest suggestions can lead to a case where something unexpected (for the user) happens. Yes, maybe it is not 100% clear if `Clear and import from file` is also importing metadata and dictionaries, but this is something one could read in the documentation.

**Comment by klues** [comment]
Implemented my latest suggestion in the [current release](https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2020-04-24-13.10%2F%2B0200) and updated [documentation](https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/02_navigation.md#additional-options) (I'm currently noticing: only text, not image).

If I implement OBF export some day, maybe we have to discuss again which options make most sense.

I'm closing this issue since it's originally a report of a bug which is already fixed since some time.
