### ISSUE TITLE
Mange Grids: Preview Thumbnail missing after import

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#63]
## Problem

When importing a grid or several grids through "Mange Grids / More / Clear all and import from file", the thumbnails of the grids are not shown, see screenshot:

![image](https://user-images.githubusercontent.com/4621810/86215984-9e568d80-bb7d-11ea-97c5-6b62ce918c65.png)

This seems also to be the case, if you upgrade to the newest version and don't reset the database, see:

![image](https://user-images.githubusercontent.com/4621810/86216150-d8c02a80-bb7d-11ea-93ac-b4d11694544e.png)

## How to reproduce

Exract and import the following file
[my-backup.zip](https://github.com/asterics/AsTeRICS-Grid/files/4856341/my-backup.zip)

**Comment by deinhofer** [comment]
After opening a grid without thumbnail, the thumbnail exists.

**Comment by klues** [comment]
That's the case if you're importing grids that were exported with an old version of AsTeRICS Grid where thumbnails didn't exist yet. On importing grids that were exported with the current version, the thumbnails should exist (like e.g. the standard gridset, see http://prntscr.com/ufft2c ).
So this issue should occur less and less in the future and there is no better way of dealing with old data since the thumbnails can only be created, if the grid is shown (screenshot is taken).
