### ISSUE TITLE
Loading of grid.asterics.eu shows blank page after grid update

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#9]
Just tried to open grid.asterics.eu
1. the spinner was shown, indicating an update of the grid
2. then the spinner disappeared and the page stayed blank.

## System environment
* Firefox 67.0.4
* Ubuntu 18.04

## Web console
The console shows the following error:

![image](https://user-images.githubusercontent.com/4621810/61740755-b92a5a80-ad8f-11e9-86f5-b8c56cf88b2e.png)

**Comment by klues** [comment]
This is a really bad issue. I've also already once encountered it with my user.

`ccm: tag doesn't match` means that the decryption of the database content fails. This means that if I/we do not find the reason and a way to fix this issue, the data of this user is lost. In your case I assume that it's a test user and it's not that fatal, but if it happens to a real user, it's really bad.

I have no clue how this could happen. In the latest update of AsTeRICS Grid I didn't change anything that could affect the code for encryption or decryption, just the caching issue of #8. 

When was the last time you opened AsTeRICS Grid with this browser? If was a longer time ago, maybe something changed in the meantime that could cause this error, but if not, I really have no clue.

However, until this is issue is solved, we should encourage endusers to make backups to file.

**Comment by klues** [comment]
OK, I almost certainly at least found the reason of the problem:
Your user and my broken user have two "meta-data" objects in the database. This object contains data like the last opened grid or input options and normally there should be only a single "meta-data" object for every user.

I use the ID of this metadata object as a salt for calculating the encryption key, because it has good properties for an encryption salt:
1) it's relatively random and different for every user
2) it doesn't change over time since there is (or should) always be only a single metadata object

I don't know how it happened that there are suddenly two meta-data objects, I'll investigate and try to find a solution.

**Comment by klues** [comment]
yeah, managed to solve the issue with https://github.com/asterics/AsTeRICS-Grid/commit/d057b27304ae0f0bbbf2eaa3f36e9250f844ec91 😃 

my broken user now works again, please try to verify with your user.

**Comment by deinhofer** [comment]
looks good :-)

It worked. :-) The console nevertheless showed one unhandled promise rejection:

![image](https://user-images.githubusercontent.com/4621810/61829047-61135700-ae68-11e9-921e-c01522780702.png)

**Comment by ChrisVeigl** [comment]
congratulations!! great work !!

**Comment by klues** [comment]
@deinhofer: does this rejection occur now everytime you open the grid or did it happen just once? It happens in `core_js` which is a collection of polyfills (javascript codesnippets that implement some functionality that is not supported in an older browser) - normally this shouldn't be needed in a current chrome or firefox...

**Comment by deinhofer** [comment]
When reloading the page now, I get the following console messages:

![image](https://user-images.githubusercontent.com/4621810/61996156-6f908700-b091-11e9-8d58-03e2231c59c7.png)

Are the ```Content-Security-Policy``` entries relevant?
Is the warning about the [scroll-link](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects) effect relevent?

**Comment by klues** [comment]
This is strange, I don't see these messages either in Firefox or in Chrome.

1. CSP: we should try the [report-uri](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#Enabling_reporting) property in addition with something like [PostBin](https://postb.in/) in order to examine what causes this error -> let's do it when we are both in the office again.
2. I don't do any scroll-linked positioning effect, no clue why your Firefox thinks so. Despite the content views (login, manage grids, about, ...) there is no scrolling at all in AsTeRICS Grid.

**Comment by klues** [comment]
@deinhofer: do you still see this "Content Security Policy" errors when opening AsTeRICS Grid?

**Comment by deinhofer** [comment]
hmm, no the last time I didn't see it. Maybe let's check it once more with the next update

**Comment by klues** [comment]
@deinhofer please test again so that we can close this issue

**Comment by deinhofer** [comment]
it never happened again, since then. so let's close it.

**Comment by klues** [comment]
perfect, thanks 👍
