### ISSUE TITLE
Connection to ARE/AREBaseURI doesn't work in Safari on MacOS Catalina

### ISSUE THREAD

**Issue by katias19** [asterics/AsTeRICS-Grid#95]
<img width="1425" alt="Bildschirmfoto 2021-06-07 um 11 52 08" src="https://user-images.githubusercontent.com/56556413/120997139-41008e80-c787-11eb-9e21-b52866ee8072.png">
<img width="1424" alt="Bildschirmfoto 2021-06-07 um 11 55 13" src="https://user-images.githubusercontent.com/56556413/120997151-4362e880-c787-11eb-8e5a-176f2525ed4e.png">

Hi,

using Asterics Grid, it's not possible to connect Asterics Actions - ARE connection doesn't work (pls check the errors in the browser console attached) under Safari 14.0.3 in MacOS Catalina 10.15.7. Also online Configuration Suite has the same problem (screenshot attached). The same works in Firefox under the same system without any issues.

Thx & kind regards

**Comment by klues** [comment]
Hi,
thanks for reporting the issue. It's caused by the fact that Safari doesn't allow "mixed content" connections to localhost, which means connecting to a non-HTTPS resource on localhost from an HTTPS-page. Also see the discussion here: https://bugs.webkit.org/show_bug.cgi?id=171934
This is a general security discussion, where Chrome and Firefox decided to allow this kind of requests, while Safari does not, see: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#loading_mixed-content_resources

So the only solution for now is to use Firefox or Chrome.

**Comment by deinhofer** [comment]
Hi,
@katias19 could you please test, if connecting to the following ARE-URI solves the problem when running AsTeRICS grid in Safari on the Mac?
```
https://127.0.0.1:8083
```
